# NumPy Part 2

![alt text](https://codelearnstorage.s3.amazonaws.com/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

`numpy` is one of the most essential libraries for Machine Learning and Deep Learning as it allows us to work with large, multi-dimensional arrays and matrices, and perform high-level mathematical functions on these arrays. 

# Set up

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import warnings
warnings.filterwarnings('ignore')

sns.set_style("whitegrid")

# Indexing

Keep in mind that when indexing the row and column, indices start at 0. And like indexing with lists, we can use negative indices as well (where -1 is the last item).

<div align="left">
<img src="https://i.imgur.com/y0CL0S4.png" width="300">
</div>

In [16]:
# Indexing
x = np.array([1, 2, 3])
print ("x: ", x)

# Lấy giá trị đầu tiên:
print ("x[0]: ", x[0])

x:  [1 2 3]
x[0]:  1


In [17]:
x

array([1, 2, 3])

In [18]:
# Assigned new value:
x[0:2] = 0
x

array([0, 0, 3])

In [20]:
x[-1] = 4
x

array([0, 0, 4])

In [23]:
# Slicing with matrix:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]]) 
print (x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print ("x 3rd column: ", x[:, 2]) 

x 3rd column:  [ 3  7 11]


In [25]:
# Step: Lấy cột đầu tiên và cột thứ 3:
x[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [26]:
# Lấy dòng thứ 2:
print ("x 2nd row: ", x[1, :]) 

x 2nd row:  [5 6 7 8]


In [27]:
# Lấy dòng cuối cùng:
print ("x last row: \n", x[-1, :]) 

x last row: 
 [ 9 10 11 12]


In [42]:
# Slicing with 3-dim array:
x = np.array(range(24)).reshape((2,3,4))
print(x)
print(x.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [43]:
x.ndim

3

In [44]:
x[0,:,:] # x[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
x[1,:,:] # x[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# Question: how can I get the second row of the second matrix?
x[1,1,:]

array([16, 17, 18, 19])

In [ ]:
# Question: how can I get the last column of the first matrix?
x[0,:,-1]

array([ 3,  7, 11])

In [ ]:
# Question: how can I get [17, 18]:
x[1, 1, 1:3]

array([17, 18])

In [48]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [52]:
# Boolean array indexing
x = np.array([[1, 3], [2, 4], [5, 6]])
print(x.shape)
print ("x:\n", x)
print('=='*10)
print ("x > 2:\n", x > 2)
print('=='*10)
print ("x[x > 2]:\n", x[x > 2])  

(3, 2)
x:
 [[1 3]
 [2 4]
 [5 6]]
x > 2:
 [[False  True]
 [False  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


# np.where
`np.where({condition}, {value to replace when meet condition}, {value to replace when NOT meet condition})`


Transform an element based on a condition

In [54]:
a= np.random.randint(0,10, size = 10)
a

array([8, 9, 1, 4, 2, 8, 0, 0, 0, 0])

In [56]:
# trả về index những số thỏa điều kiện 
np.where(a>3)[0] 

array([0, 1, 3, 5], dtype=int64)

In [74]:
# thay nhuững giá trị >3 thành -1, ngược lại thì trả 0
np.where(a>3, -1, 0)

array([-1, -1, -1,  0,  0,  0, -1,  0, -1, -1])

In [75]:
# thay nhuững giá trị >3 thành -1, ngược lại thì vẫn giữ nguyên
np.where(a>3, -1, a)

array([-1, -1, -1,  3,  2,  0, -1,  2, -1, -1])

# Transposing

We often need to change the dimensions of our matrix for operations like matrix multiplication

To transpose a matrix there are two steps:
1. Rotate the matrix 90°
2. Reverse the order of elements in each row (e.g. [a b ] becomes [b a])


<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/foundations/numpy/transpose.png" width="400">
</div>

- Syntax: `array.T (or np.transpose(array, (1,0))`

In [63]:
x = np.array([[1,2,3], [4,5,6]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
x_transpose= x.T
print ("X transpose:\n", x_transpose)
print ("X.T shape: ", x_transpose.shape)


x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
X transpose:
 [[1 4]
 [2 5]
 [3 6]]
X.T shape:  (3, 2)


In [58]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# another way of using np transpose
x_transpose = np.transpose(x, (1,0)) # flip dimensions at index 0 and 1
print ("X transpose:\n", x_transpose)
print ("X transpose shape: ", x_transpose.shape)


X transpose:
 [[1 4]
 [2 5]
 [3 6]]
X transpose shape:  (3, 2)


# Reshaping

Sometimes, we'll need to alter the dimensions of the matrix. **Reshaping allows us to transform a tensor into different permissible shapes** -- our reshaped tensor has the same amount of values in the tensor. (1X6 = 2X3).**We can also use `-1` on a dimension and NumPy will infer the dimension based on our input tensor.**

The way reshape works is by looking at each dimension of the new tensor and separating our original tensor into that many units. So here the dimension at index 0 of the new tensor is 2 so we divide our original tensor into 2 units, and each of those has 3 values.

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/foundations/numpy/reshape.png" width="450">
</div>

In [70]:
# Reshaping
x = np.array([1,2,3,4,5,6])
print (x)
print ("x.shape: ", x.shape)

[1 2 3 4 5 6]
x.shape:  (6,)


In [74]:
# Reshape thành matrix 2x3
y = np.reshape(x, (2, 3))
print ("y: \n", y)
print ("y.shape: ", y.shape)

y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


In [72]:
# Reshape thành matrix có 3 cột:
z = np.reshape(x, (-1, 3))
print ("z: \n", z)
print ("z.shape: ", z.shape)

z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


In [75]:
# Reshape thành matrix có 3 dòng:
z = np.reshape(x, (3, -1))
print ("z: \n", z)
print ("z.shape: ", z.shape)

z: 
 [[1 2]
 [3 4]
 [5 6]]
z.shape:  (3, 2)


In [81]:
# Reshape thành array 3-dim có shape là: (3, 1, 2)
z = np.reshape(x, (3, 1, 2))
print(z)

[[[1 2]]

 [[3 4]]

 [[5 6]]]


# Adding/removing dimensions

We can also easily add and remove dimensions to our tensors and we'll want to do this to make tensors compatible for certain operations.

Example of expand_dims in matrix multiplication

In [103]:
# Adding dimensions
x = np.array([1,2,3])
print ("x:\n", x) 
print ("x.shape: ", x.shape)
y = np.expand_dims(x, axis=[1]) # expand dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)   # notice extra set of brackets are added

x:
 [1 2 3]
x.shape:  (3,)
y: 
 [[1]
 [2]
 [3]]
y.shape:  (3, 1)


In [106]:
# Adding dimensions
x = np.array([[1,2,3], [4,5,6]])
print ("x:\n", x) 
print ("x.shape: ", x.shape)
y = np.expand_dims(x, axis=[1]) # expand dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)   # notice extra set of brackets are added

x:
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape:  (2, 1, 3)


In [111]:
# Removing dimensions
x = np.array([[[1,2,3]],[[4,5,6]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.squeeze(x, axis=1) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)  # notice extra set of brackets are gone

x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


In [112]:
# Removing dimensions
x = np.array([[[1,2,3]],[[4,5,6]]])
print ("x:\n", x)
print ("x.shape: ", x.shape)
y = np.squeeze(x) # squeeze dim 1
print ("y: \n", y)
print ("y.shape: ", y.shape)  # notice extra set of brackets are gone

x:
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


# Arithmetic


In [113]:
# Basic math
x = np.array([[1,1], [2,2]], dtype=np.float64)
y = np.array([[2,2], [3,3]], dtype=np.float64)
print(x)
print('-'*10)
print(y)
print('-'*10)

print ("x + y:\n", np.add(x, y)) # or x + y
print('-'*10)

print ("x - y:\n", np.subtract(x, y)) # or x - y
print('-'*10)

print ("x * y:\n", np.multiply(x, y)) # or x * y (different from x@y)

[[1. 1.]
 [2. 2.]]
----------
[[2. 2.]
 [3. 3.]]
----------
x + y:
 [[3. 3.]
 [5. 5.]]
----------
x - y:
 [[-1. -1.]
 [-1. -1.]]
----------
x * y:
 [[2. 2.]
 [6. 6.]]


### Axis operations

We can also do operations across a specific axis.

<div align="left">
<img src="https://raw.githubusercontent.com/GokuMohandas/MadeWithML/main/images/foundations/numpy/axis.gif" width="450">
</div>

In [114]:
# Sum across a dimensionwhe
x = np.array([[1,2,3],[3,4,5]])

print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

[[1 2 3]
 [3 4 5]]
sum all:  18
sum axis=0:  [4 6 8]
sum axis=1:  [ 6 12]


In [116]:
# Sum across a dimension
x = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print (x)
print (x.shape)
print ("sum all: ", np.sum(x)) # adds all elements

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
(3, 4)
sum all:  30


In [119]:
# question: to have this output [10,10,10], what should be the axis here?
sum_axis1 = np.sum(x, axis=1)
print("sum: ", sum_axis1) # sum across rows


sum:  [10 10 10]


In [121]:
# question: to have this output [3,6,9,12], what should be the axis here?
sum_axis0 = np.sum(x, axis=0)
print("sum: ", sum_axis0) # sum across rows

sum:  [ 3  6  9 12]


Những hàm dùng nhiều nhất: min,max,mean,var,std,sum 

In [123]:
# Min/max
x = np.array(
              [[1,2,3], 
               [44,45,0]]   
              )
print(x)
print(x.shape)
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

[[ 1  2  3]
 [44 45  0]]
(2, 3)
min:  0
max:  45
min axis=0:  [1 2 0]
min axis=1:  [1 0]


# Broadcasting

What is broadcasting

- the matrix of the smaller shape is expanded to match the matrix of the bigger shape
- Only when shapes are **compatible** when trying to do an elementwise operation

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

When operating on two arrays, NumPy compares their shapes element-wise. It **starts with the trailing (most right) dimensions and works its way to the left**. Two dimensions are compatible when
- they are equal, or
- one of them is 1

If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

**Matrix and scalar**

Use case: Normalize **entire** your dataset by subtracting **the mean (a scalar)** from the entire data set (a matrix) and dividing by the **standard deviation (another scalar)**

In [135]:
# Case1: matrix (3, 4) +  (4,)
a = np.array([[4, 3, 9, 1],
            [6, 2, 3, 6],
            [10, 3, 2, 1]])

b = np.array([1, 2, 3, 4])

print('array a:\n', a)
print('shape of a:', a.shape)
print('=='*15)
print('array b:\n', b)
print('shape of b:', b.shape)
print('=='*15)
print('a + b:\n', a + b)

array a:
 [[ 4  3  9  1]
 [ 6  2  3  6]
 [10  3  2  1]]
shape of a: (3, 4)
array b:
 [1 2 3 4]
shape of b: (4,)
a + b:
 [[ 5  5 12  5]
 [ 7  4  6 10]
 [11  5  5  5]]


In [136]:
# Case2: matrix (3, 4) +  (3,)
a = np.array([[4, 3, 9, 1],
            [6, 2, 3, 6],
            [10, 3, 2, 1]])

b = np.array([1, 2, 3])

print('array a:\n', a)
print('shape of a:', a.shape)

print('=='*15)

print('array b:\n', b)
print('shape of b:', b.shape)

print('=='*15)

print('a + b:\n', a + b)

array a:
 [[ 4  3  9  1]
 [ 6  2  3  6]
 [10  3  2  1]]
shape of a: (3, 4)
array b:
 [1 2 3]
shape of b: (3,)


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [139]:
# Case2: matrix (3, 4) +  (3,). 
# Để có thể broadcast được ta cần phải thêm 1 chiều vào axis 1 của ma trận b: 
a = np.array([[4, 3, 9, 1],
            [6, 2, 3, 6],
            [10, 3, 2, 1]])

b = np.array([1, 2, 3])
b = np.expand_dims(b, axis = [1]) #b = b[:,np.newaxis]

print('array a:\n', a)
print('shape of a:', a.shape)

print('=='*15)

print('array b:\n', b)
print('shape of b:', b.shape)

print('=='*15)

print('a + b:\n', a + b)

array a:
 [[ 4  3  9  1]
 [ 6  2  3  6]
 [10  3  2  1]]
shape of a: (3, 4)
array b:
 [[1]
 [2]
 [3]]
shape of b: (3, 1)
a + b:
 [[ 5  4 10  2]
 [ 8  4  5  8]
 [13  6  5  4]]


# Question

Check whether these matrices can be broadcasted, using the broadcasting rule

- A matrix of shape (2,3) + a vector of shape (3,)
- A matrix of shape (2,3) + a vector of shape (2,)
- A matrix of shape (3,2) + a matrix of shape (3,)
- A matrix of shape (2,3) + a 3d tensor of shape (4,2,3)
- A matrix of shape (3,2) + a 3d tensor of shape (4,2,3)

